#apiVersion: v1.0
#kind: Pod
#metadata:
#  name: nginx
#spec:
#  containers:
#    - name: nginx-container
#      image: nginx:mainline-alpine3.18-slim
#      port: 80
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
        - containerPort: 80
